### ISSUE TITLE
Question about DWM in Win11.

### ISSUE THREAD

**Issue by Aspector1** [Ingan121/DWMKiller#2]
Dude, your script is awesome! But is it possible to turn off dwm in win11 without logging out?

**Comment by Ingan121** [comment]
No. Win11 requires removal/rename of dwminit.dll, which is loaded by Winlogon at login. Just killing DWM without renaming it will make the mouse completely unusable.

**Comment by Aspector1** [comment]
> No. Win11 requires removal/rename of dwminit.dll, which is loaded by Winlogon at login. Just killing DWM without renaming it will make the mouse completely unusable.

Ok, thanks for the answer! But can I ask one more question? Is it possible to turn off DWM for specific programs?

**Comment by Ingan121** [comment]
If you mean having a program with DWM alongside another program without DWM, this is simply impossible because that's not how DWM works. (If you just want the Basic frame, use my [BasicThemer2](/Ingan121/BasicThemer2).)
If you mean turning DWM off when a specific program is running (like Win7's disable composition compat option), although possible, it would not be that usable in Win11 as it requires re-login.

**Comment by Aspector1** [comment]
> If you mean turning DWM off when a specific program is running (like Win7's disable composition compat option), although possible, it would not be that usable in Win11 as it requires re-login.

So this means that compat layer DISABLEDWM no longer works, right?
